# serverless.yml

service: python-api

provider:
    name: aws
    runtime: python3.8
    stage: dev
    region: us-east-2

plugins:
  - serverless-layers
custom:
    serverless-layers:
        - staticArn:
            functions:
                - usgsDataAccess
            arn:
                - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-python38-numpy:12
                - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-python38-numpy:12

functions:
    usgsDataAccess:
        handler: usgsController.getUSGSDefaultData
        events:
            - http:
                path: /
                method: get
