# serverless.yml

app: flowcasts-backend

service: python-api
package:
    patterns:
        - 'app/**'

provider:
    name: aws
    deploymentMethod: direct
    runtime: python3.10
    stage: ${sls:stage}
    region: us-east-2
    timeout: 30
    ecr:
        images:
            prophet-image:
                path: ./
functions:
    usgsDefaultDataAccess:
        handler: app/controllers/usgs_controller.get_usgs_default_data
        layers:
            - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p310-pandas:3
        events:
            - http:
                  path: /
                  method: get
                  cors: true
    usgsDailyAverageData:
        handler: app/controllers/usgs_controller.get_daily_average_data
        layers:
            - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p310-pandas:3
        events:
            - http:
                  path: /daily-average-data
                  method: get
                  cors: true
    usgsDailyRunnablePercentage:
        handler: app/controllers/usgs_controller.get_daily_runnable_percentage
        layers:
            - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p310-pandas:3
        events:
            - http:
                  path: /runnable-percentage
                  method: get
                  cors: true
    prophetForecast:
        ecr:
        image: prophet-image
        events:
            - http:
                  path: /prophet_base_forecast
                  method: get
                  cors: true
