# serverless.yml

app: flowcasts-backend
service: python-api

provider:
    name: aws
    stage: ${sls:stage}
    runtime: python3.8
    region: us-east-2
    timeout: 30
    ecr:
        images:
            neural-prophet:
                path: ./app/

functions:
    neural-prophet-forecast:
        image:
            name: neural-prophet
        events:
            - http:
                  path: /neural_forecast
                  method: get
                  cors: true
