# serverless.yml

app: flowcasts-backend
service: python-api

provider:
    name: aws
    stage: ${sls:stage}
    runtime: python3.8
    region: us-east-2
    timeout: 30
    memorySize: 4096

functions:
    neural-prophet-forecast:
        image: 746562334669.dkr.ecr.us-east-2.amazonaws.com/river-forecast@sha256:79c4b9d0a06b18f63f39327f3151660cb90d2c5d381110dfc15d58036619bd58
        events:
            - http:
                  path: /neural_forecast
                  method: get
                  cors: true
