# serverless.yml

service: python-api

provider:
    name: aws
    runtime: python3.8
    stage: dev
    region: us-east-2
    deploymentBucket:
        name: static-arn-bucket

plugins:
  - serverless-layers
  - serverless-deployment-bucket

custom:
    serverless-layers:
        - NumpyArn:
            functions:
                - usgsDefaultDataAccess
                - usgsDailyAverageData
                - usgsDailyRunnablePercentage
            arn: arn:aws:lambda:us-east-2:770693421928:layer:Klayers-python38-numpy:12
        - PandasArn:
            functions:
                - usgsDefaultDataAccess
                - usgsDailyAverageData
                - usgsDailyRunnablePercentage
            arn: arn:aws:lambda:us-east-2:770693421928:layer:Klayers-python38-pandas:23

functions:
    usgsDefaultDataAccess:
        handler: usgsController.getUSGSDefaultData
        events:
            - http:
                path: /
                method: get
    usgsDailyAverageData:
        handler: usgsController.getDailyAverageData
        events:
            - http:
                path: /getDailyAverageData
                method: get
    usgsDailyRunnablePercentages:
        handler: usgsController.getDailyRunnablePercentages
        events:
            - http:
                path: /getRunnablePercentages
                method: get
            
